version: '3.7'

services:
  api:
    build: .
    command: bash -c "bash prestart.sh && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    restart: always  
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    env_file:
      - .env
    image: postgres:11
    ports:
      - "5432:5432"
    

volumes:
  db-data:
