"""Profits

Revision ID: 4b38589a8dad
Revises: a8e6f72dc606
Create Date: 2020-07-31 00:24:39.314458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b38589a8dad"
down_revision = "a8e6f72dc606"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["invest_id"], ["invest.id"]),
        sa.Column("returns", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profit")
    op.drop_column('invest', 'returns') 

