"""Investments migration

Revision ID: a8e6f72dc606
Revises: d4867f3a4c0a
Create Date: 2020-07-27 03:01:22.864273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8e6f72dc606"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("lock_period", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_investment_name"), "investment", ["name"], unique=True)
    op.create_index(op.f("ix_investment_description"), "investment", ["description"])
    op.create_index(op.f("ix_investment_rate"), "investment", ["rate"])
    op.create_index(op.f("ix_investment_lock_period"), "investment", ["lock_period"])
    op.create_index(op.f("ix_investment_id"), "investment", ["id"], unique=False)

    op.create_table(
        "wallet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "invest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("returns", sa.Integer(), nullable=True),
        sa.Column("potential_returns", sa.Integer(), nullable=False),
        sa.Column("duration", sa.String(), nullable=False),
        sa.Column("investment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['investment_id'], ['investment.id']),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column('transaction_type', sa.Enum('withdraw', 'deposit', 'debit', 'credit','generic', name='ReferenceTypes')),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_investment_id"), table_name="investment")
    op.drop_index(op.f("ix_investment_name"), table_name="investment")
    op.drop_index(op.f("ix_investment_description"), table_name="investment")
    op.drop_index(op.f("ix_investment_rate"), table_name="investment")
    op.drop_index(op.f("ix_investment_lock_period"), table_name="investment")
    op.drop_table("investment")
    op.drop_table("wallet")
    op.drop_table("invest")
    op.drop_table("transaction")

